services:
    backend:
        build: ./server
        container_name: backend_app
        ports:
            - "3000:3000"
        env_file:
            - ./server/.env
        environment:
            - DATABASE_URL=postgresql://postgresql:postgresql_password@db:5432/plan_calculator
            - RESEND_API_KEY=re_bscq6LWg_8QYkbRzvxdeYfF9rhPEfhjcn
            - JWT_SECRET=mySuperSecretJWTKey
        depends_on:
            - db
        volumes:
            - ./server:/app
        restart: unless-stopped
        command: sh -c "npx prisma generate && npx prisma migrate deploy && npm run seed && npm run dev"

    web:
        build: ./web
        container_name: frontend_app
        ports:
            - "5173:5173"
        environment:
            - VITE_API_URL=http://localhost:3000
        volumes:
            - ./web:/app
            - /app/node_modules
        depends_on:
            - backend
        restart: unless-stopped

    db:
        image: bitnami/postgresql:latest
        environment:
            - POSTGRES_USER=postgresql
            - POSTGRES_PASSWORD=postgresql_password
            - POSTGRES_DB=plan_calculator
        ports:
            - "5432:5432"
        volumes:
            - db_data:/bitnami/postgresql
        restart: unless-stopped

volumes:
    db_data:
