services:
    # backend:
    #     build: ./server
    #     container_name: backend_app
    #     ports:
    #         - "3000:3000"
    #     env_file:
    #         - ./server/.env
    #     depends_on:
    #         - db
    db:
        image: bitnami/postgresql:latest
        environment:
            - POSTGRES_USER=postgresql
            - POSTGRES_PASSWORD=postgresql_password
            - POSTGRES_DB=plan_calculator
        ports:
            - "5432:5432"
        volumes:
            - db_data:/bitnami/postgresql

volumes:
    db_data:
