# Variáveis
@baseUrl = http://localhost:3000

### Login

POST {{baseUrl}}/login
Content-Type: application/json

{
  "username": "admin",
  "password": "desafio"
}

###

## Calcular plano recomendado
POST {{baseUrl}}/calcular-plano
Content-Type: application/json

{
    "phones": 4,
    "computers": 2,
    "smartTvs": 2,
    "tvBox": 0,
    "others": 3,
    "gamer": true
}

###

POST {{baseUrl}}/criar-venda
Content-Type: application/json

{
  "name": "Fabiano",
  "email": "emerson.nascimento@example.com",
  "telephone": "77981111111",
  "planId": "639b0494-9c22-4c71-8b39-d10cbbee6ab8",
  "weightTotal": 5.5,
  "devices": {
    "phones": 2,
    "computers": 3,
    "smartTvs": 1,
    "tvBox": 4,
    "others": 2,
    "gamer": true
  }
}

###

POST {{baseUrl}}/admin/upload-vendas
Content-Type: multipart/form-data
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQwMzAwZTA5LWYyMjktNDg3MC1iNDUxLTc5YmUwMjk1NTcxYSIsInVzZXJuYW1lIjoiYWRtaW4iLCJpYXQiOjE3NTYwNzQzNTgsImV4cCI6MTc1NjA3Nzk1OH0.vVJ3ngi5175grvYp-LNIiUqSgivrtNVihMHYJwquXRc

{
  "file": "../dados_fake_clientes_opcional.xlsx"
}

###

GET {{baseUrl}}/admin/vendas
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQ3NGQ4MmJhLWExOWUtNDI5ZC1iZWE2LWVhNmZjYjBkZDdjYyIsInVzZXJuYW1lIjoiYWRtaW4iLCJpYXQiOjE3NTYxNjI3NzcsImV4cCI6MTc1NjE2NjM3N30.TCvV11PYW9Q_u1dkD9YMoVJ_bn2vkF5zPNuBFlQQHCI
Content-Type: application/json

### 

GET {{baseUrl}}/sale/78477868-56a2-4971-b4a4-5d136913992b
Content-Type: application/json

###  

GET {{baseUrl}}/admin/metrics
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQ3NGQ4MmJhLWExOWUtNDI5ZC1iZWE2LWVhNmZjYjBkZDdjYyIsInVzZXJuYW1lIjoiYWRtaW4iLCJpYXQiOjE3NTYxNjYwNTUsImV4cCI6MTc1NjE2OTY1NX0.ZMkLiMDplBrQIlMom7I_vWb5K-cx_c4n6ccaXHAzLvs
