# Variáveis
@baseUrl = http://localhost:3000

### Login

POST {{baseUrl}}/login
Content-Type: application/json

{
  "username": "admin",
  "password": "desafio"
}

###

## Calcular plano recomendado
POST {{baseUrl}}/calcular-plano
Content-Type: application/json

{
    "phones": 4,
    "computers": 2,
    "smartTvs": 2,
    "tvBox": 0,
    "others": 3,
    "gamer": true
}

###

POST {{baseUrl}}/criar-venda
Content-Type: application/json

{
  "nome": "Fabiano",
  "email": "emerson.nascimento@example.com",
  "telefone": "77981111111",
  "planoId": "a52d6c43-01e6-4d89-b10d-96c2e77b0162",
  "pesoTotal": 5.5,
  "dispositivos": {
    "celulares": 2,
    "computadores": 3,
    "smartTvs": 1,
    "tvBox": 4,
    "outros": 2,
    "gamer": true
  }
}

###

POST {{baseUrl}}/upload-vendas
Content-Type: multipart/form-data

{
  "file": "../dados_fake_clientes_opcional.xlsx"
}

###

GET {{baseUrl}}/admin/vendas
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQ4MjNmZjVhLTMxYjEtNGViZC1iZmUwLTFhZTc2ZmJiNDhhMCIsInVzZXJuYW1lIjoiYWRtaW4iLCJpYXQiOjE3NTU3MDA5NDEsImV4cCI6MTc1NTcwNDU0MX0.ssTRLD41-qaVH4AnP_LOvE4ZzfvKnVa8sRfaitJzvG0
Content-Type: application/json

### 

GET {{baseUrl}}/sale/78477868-56a2-4971-b4a4-5d136913992b
Content-Type: application/json

